name: ci pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-code
        uses: actions/checkout@v5

      - name: Installing node
        uses: actions/setup-node@v3
        with :
          node-version: 16

      - name: Installing deps
        uses: npm install 
    
      - name: Testing 
        uses: npm test